export const categories = [
    "Action",
    "Adventure",
    "Comedy",
    "Drama",
    "Fantasy",
    "Horror",
    "Mystery",
    "Romance",
    "Sci-Fi",
    "Thriller",
    "Western",
    "Animation",
    "Family",
    "Music",
    "Documentary",
    "War",
    "History",
    "Sport",
    "Crime",
    "Biography",
    "Musical",
    "Short",
    "Film-Noir",
    "Adult",
    "Talk-Show",
    "Game-Show",
    "Reality-TV",
    "News",
    "Shooter",
    "Survival",
    "Racing",
    "Puzzle",
    "Platformer",
    "RPG",
    "MMO",
    "MOBA",
    "Sandbox",
    "Open World",
    "Stealth",
    "Turn-Based",
    "Real-Time",
    "Turn-Based Strategy",
    "Real-Time Strategy",
    "Tactical",
    "Role-Playing",
    "Hack and Slash",
    "Visual Novel",
    "Text-Based",
    "Card Game",
    "Trivia",
    "Pinball",
    "Arcade",
];
